FROM nginx:alpine

RUN mkdir /etc/nginx/sites-available \
&& mkdir /etc/nginx/sites-enabled \
&& rm -f /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh \

# Remove default nginx config
&& rm -f /etc/nginx/nginx.conf \
&& rm -f /etc/nginx/conf.d/default.conf

# Add nginx global config
ADD ./docker/config/nginx.conf /etc/nginx/nginx.conf
