<?php


namespace app\models;


use yii\behaviors\SluggableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;

class Article extends ActiveRecord
{
    public $category_id;

    public static function tableName()
    {
        return '{{article}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => SluggableBehavior::className(),
                'attribute' => 'name',
                'slugAttribute' => 'seo_url',
                'immutable' => true
            ],
       ];
    }

    public function rules()
    {
        return [
            [['id', 'active'], 'integer'],
            [['name', 'seo_url', 'short_desc', 'description'], 'string'],
            [['name', 'description', 'category_id'], 'required'],
            [['dt_create'], 'default', 'value' => null],
            [['dt_create'], 'date', 'format' => 'php:Y-m-d'],
            [['category_id'], 'safe']
        ];
    }

    public function attributeLabels()
    {
        return [
            'name' => 'Наименование',
            'seo_url' => 'Ссылка на новость',
            'dt_create' => 'Дата создания',
            'short_desc' => 'Короткое описание',
            'description' => 'Описание',
            'active' => 'Активность',
            'id' => 'Номер',
            'category_id' => 'Категория'
        ];
    }
    public function beforeValidate()
    {
        if (!empty($this->dt_create)) $this->dt_create = date_format(new \DateTime($this->dt_create), 'Y-m-d');
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function getCategory()
    {
        return $this->hasMany(Category::className(), ['id' => 'category_id'])
            ->viaTable('article_category', ['article_id' => 'id']);
    }
    public function getCategoryName()
    {
        return (isset($this->category[0]->name))?$this->category[0]->name : null;
    }
    public function getCategoryId()
    {
        return (isset($this->category[0]->id))? $this->category[0]->id : null;
    }

    public function afterSave($insert, $changedAttributes)
    {
        $ArticleCategory = ArticleCategory::findOne(['article_id' => $this->id]);
        if (is_object($ArticleCategory)) $ArticleCategory->delete();
        $ArticleCategory = new ArticleCategory(['article_id' => $this->id, 'category_id' => $this->category_id]);
        $ArticleCategory->save();
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}